# Site settings
title: Ab
description: "Let's write less code"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "https://binaryja.cc" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# User settings
username: ab
user_title: Ab
email: site[at]binaryja.cc
twitter_username: 
github_username: abdala
linkedin_public_url: 
profile_picture: https://pbs.twimg.com/profile_images/985598325541015553/uzkyOsgZ_400x400.jpg 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
  section_2:
    - title: github
      url: http://www.github.com/abdala
      new_tab: true
      key_trigger: g
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Cache server for AWS Secrets Manager
    url: https://github.com/cgauge/aws-secretsmanager-caching-extension
  - name: Task Manager Library
    url: https://github.com/cgauge/task-manager-lib
  - name: Password Strength Library
    url: https://github.com/cgauge/password-strength-lib

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
